graph LR
A[START] --> B[PUSH DS]
B --> C[MOV AX, 0000H]
C --> D[MOV DS, AX]
D --> E[MOV SI, 3500H]
E --> F[MOV DI, 3600H]
F --> G[MOV CX, 8]
G --> H[MOV AL, [SI]]
H --> I[MOV [DI], AL]
I --> J[INC SI]
J --> K[INC DI]
K --> L[LOOP AA1]
L --> M[INT 21H]
M --> N[END]
